CREATE TABLE IF NOT EXISTS wb_product_cards (
    id SERIAL PRIMARY KEY,
    nm_id BIGINT NOT NULL UNIQUE,
    imt_id BIGINT,
    nm_uuid VARCHAR(100),
    subject_id INTEGER,
    subject_name VARCHAR(255),
    vendor_code VARCHAR(255),
    brand VARCHAR(255),
    title VARCHAR(500),
    description TEXT,
    video_url TEXT,
    dimensions_length INTEGER,
    dimensions_width INTEGER,
    dimensions_height INTEGER,
    dimensions_weight_brutto DECIMAL(10,3),
    dimensions_is_valid BOOLEAN,
    characteristics JSONB,
    sizes JSONB,
    photos_big TEXT[],
    photos_c246x328 TEXT[],
    photos_c516x688 TEXT[],
    photos_square TEXT[],
    photos_tm TEXT[],
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    synced_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS wb_cards_sync_log (
    id SERIAL PRIMARY KEY,
    job_start TIMESTAMPTZ NOT NULL,
    job_end TIMESTAMPTZ,
    status VARCHAR(50) DEFAULT 'running',
    date_from DATE,
    date_to DATE,
    cards_fetched INTEGER DEFAULT 0,
    cards_inserted INTEGER DEFAULT 0,
    cards_updated INTEGER DEFAULT 0,
    http_requests INTEGER DEFAULT 0,
    retries INTEGER DEFAULT 0,
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
